# Generated by Django 3.1.7 on 2021-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_belongsto'),
        ('game', '0004_auto_20210327_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='player.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameUrl',
            field=models.URLField(blank=True),
        ),
    ]
