# Generated by Django 3.1.7 on 2021-04-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_delete_playerrecord'),
        ('game', '0005_auto_20210331_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twoPointers', models.IntegerField(default=0)),
                ('twoPointersMade', models.IntegerField(default=0)),
                ('threePointers', models.IntegerField(default=0)),
                ('threePointersMade', models.IntegerField(default=0)),
                ('freethrows', models.IntegerField(default=0)),
                ('freethrowMade', models.IntegerField(default=0)),
                ('offensiveRebound', models.IntegerField(default=0)),
                ('defensiveRebound', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('turnover', models.IntegerField(default=0)),
                ('offensiveFoul', models.IntegerField(default=0)),
                ('defensiveFoul', models.IntegerField(default=0)),
                ('numberOfMinutesPlayed', models.IntegerField(default=0)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
